import type { AdapterContext } from '../core/types.js';

/**
 * Renders the common Markdown body shared by every plain-Markdown target
 * (Claude, AGENTS.md, Gemini). Cursor wraps this same body in YAML
 * frontmatter — see cursor.ts.
 */
export function renderMarkdownBody(ctx: AdapterContext, toolLabel: string): string {
  const { config, rules } = ctx;
  const lines: string[] = [];

  lines.push(`# ${config.project.name}`);
  if (config.project.description) {
    lines.push('', config.project.description);
  }
  lines.push('', generatedNotice(toolLabel));

  for (const rule of rules) {
    lines.push('', `## ${rule.title}`, '', rule.body);
  }

  return `${lines.join('\n').trimEnd()}\n`;
}

export function generatedNotice(toolLabel: string): string {
  return [
    '<!--',
    `  This file is generated by agentsync for ${toolLabel}.`,
    '  Do NOT edit it directly — your changes will be overwritten.',
    '  Edit the sources instead: agentsync.config.yaml and the fragments in rules/,',
    '  then regenerate with `agentsync build` (or verify with `agentsync check`).',
    '-->',
  ].join('\n');
}

/**
 * Serializes a string as a YAML double-quoted scalar. JSON string escaping
 * is a valid subset of YAML double-quoted scalar escaping, so JSON.stringify
 * is sufficient here without pulling in a YAML serializer for one field.
 */
export function yamlQuotedString(value: string): string {
  return JSON.stringify(value);
}
