import { describe, expect, it } from 'vitest';
import { parse as parseYaml } from 'yaml';
import {
  agentsAdapter,
  claudeAdapter,
  cursorAdapter,
  geminiAdapter,
  listAdapterIds,
  getAdapter,
  validateConfig,
  parseRuleFragment,
} from '../../src/index.js';
import type { AdapterContext } from '../../src/index.js';

const config = validateConfig({
  version: 1,
  project: { name: 'demo-project', description: 'A demo project used in tests.' },
  targets: { claude: {}, agents: {}, cursor: {}, gemini: {} },
});

const rules = [
  parseRuleFragment('00-overview.md', '# Overview\n\nThis project does things.'),
  parseRuleFragment('10-style.md', '# Coding Style\n\nUse two spaces.'),
];

const ctx: AdapterContext = { config, rules };

describe('listAdapterIds / getAdapter', () => {
  it('registers exactly the four built-in adapters', () => {
    expect(listAdapterIds().sort()).toEqual(['agents', 'claude', 'cursor', 'gemini']);
  });

  it('returns undefined for unknown ids', () => {
    expect(getAdapter('does-not-exist')).toBeUndefined();
  });
});

describe('claudeAdapter', () => {
  it('renders project name, description, generated notice, and rule sections', () => {
    const out = claudeAdapter.render(ctx);
    expect(out).toContain('# demo-project');
    expect(out).toContain('A demo project used in tests.');
    expect(out).toContain('generated by agentsync');
    expect(out).toContain('## Overview');
    expect(out).toContain('This project does things.');
    expect(out).toContain('## Coding Style');
    expect(out).toContain('Use two spaces.');
    expect(out.endsWith('\n')).toBe(true);
  });

  it('defaults to CLAUDE.md', () => {
    expect(claudeAdapter.defaultOutput).toBe('CLAUDE.md');
  });
});

describe('agentsAdapter', () => {
  it('defaults to AGENTS.md and renders the same rule content', () => {
    expect(agentsAdapter.defaultOutput).toBe('AGENTS.md');
    const out = agentsAdapter.render(ctx);
    expect(out).toContain('## Overview');
    expect(out).toContain('AGENTS.md standard');
  });
});

describe('geminiAdapter', () => {
  it('defaults to GEMINI.md', () => {
    expect(geminiAdapter.defaultOutput).toBe('GEMINI.md');
    const out = geminiAdapter.render(ctx);
    expect(out).toContain('Gemini CLI');
  });
});

describe('cursorAdapter', () => {
  it('defaults to .cursor/rules/agentsync.mdc', () => {
    expect(cursorAdapter.defaultOutput).toBe('.cursor/rules/agentsync.mdc');
  });

  it('produces valid YAML frontmatter followed by the shared body', () => {
    const out = cursorAdapter.render(ctx);
    expect(out.startsWith('---\n')).toBe(true);

    const closingIndex = out.indexOf('\n---', 4);
    const frontmatterBlock = out.slice(4, closingIndex);
    const parsed = parseYaml(frontmatterBlock) as Record<string, unknown>;
    expect(parsed.description).toBe('A demo project used in tests.');
    expect(parsed.alwaysApply).toBe(true);
    expect(parsed.globs).toBe('**/*');

    expect(out).toContain('# demo-project');
    expect(out).toContain('## Overview');
  });

  it('falls back to a generated description when none is configured', () => {
    const bareConfig = validateConfig({ version: 1, project: { name: 'bare' }, targets: { cursor: {} } });
    const out = cursorAdapter.render({ config: bareConfig, rules });
    expect(out).toContain('description:');
    expect(out).toContain('bare project rules');
  });
});
